table *Measures
	lineageTag: c5bdf72e-8ae1-460d-931d-1c51e532acd9

	measure 'Away Points' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _team2 = calculate(max(MatchupsTable[Team]),MatchupsTable[Week]=_wk,MatchupsTable[Home_Or_Away]="Away")
			var _result = CALCULATE(sum(PlayerPointsStats[TotalPoints]),PlayerPointsStats[FantasyTeam]=_team2,PlayerPointsStats[Week]=_wk)
			return _result
		displayFolder: Scoreboard
		lineageTag: 2d899964-1c5b-4b98-ab65-2bb9d4e74270

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Away Name' = calculate(max(MatchupsTable[Team]),MatchupsTable[ID]=min(MatchupsTable[ID]))
		displayFolder: Scoreboard
		lineageTag: c4ea3df8-d05a-4c50-9c9c-e797ea3985fc

	measure 'Home Name' = calculate(max(MatchupsTable[Team]),MatchupsTable[ID]=MAX(MatchupsTable[ID]))
		displayFolder: Scoreboard
		lineageTag: 02b86543-4d5a-46b1-a032-f4706ed1b9aa

	measure 'Home Points' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _team2 = calculate(max(MatchupsTable[Team]),MatchupsTable[Week]=_wk,MatchupsTable[Home_Or_Away]="Home")
			var _result = CALCULATE(sum(PlayerPointsStats[TotalPoints]),PlayerPointsStats[FantasyTeam]=_team2,PlayerPointsStats[Week]=_wk)
			return _result
		displayFolder: Scoreboard
		lineageTag: d52c3d93-78ec-43f0-a06c-02a47d763129

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Away Image' =
			
			var _team = calculate(max(MatchupsTable[Team]),MatchupsTable[ID]=min(MatchupsTable[ID]))
			return CALCULATE(max(TeamsTable[Image]),TeamsTable[Fantasy Name]=_team)
		displayFolder: Scoreboard
		lineageTag: 0c1145a7-6372-44ed-8f36-bff42168760e

	measure 'Home Image' =
			
			var _team = calculate(max(MatchupsTable[Team]),MatchupsTable[ID]=max(MatchupsTable[ID]))
			return CALCULATE(max(TeamsTable[Image]),TeamsTable[Fantasy Name]=_team)
		displayFolder: Scoreboard
		lineageTag: 9b6c691f-2748-4069-8180-0e2a3ec7c5f6

	measure 'Points Variance' = [Home Points] - [Away Points]
		displayFolder: Scoreboard
		lineageTag: 982fb7fa-6229-4ab3-8dca-b836de4a8385

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Away Text Color' = if([Points Variance]<0,"#000000","#7f8487")
		displayFolder: Scoreboard
		lineageTag: 9c450bcb-db54-4469-b8f4-52afb5304732

	measure 'Home Text Color' = if([Points Variance]>0,"#000000","#7f8487")
		displayFolder: Scoreboard
		lineageTag: eb8e750a-3b4b-4e79-9ece-ae22a4b4dc20

	measure DraftName =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _round = SELECTEDVALUE(Draft[Round])
			return calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
		displayFolder: Draft
		lineageTag: 4aa148a2-13bf-4318-a250-7026065931a8

	measure DraftPic =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = [DraftName]
			return calculate(max(UniquePlayers[Player Pic]),UniquePlayers[Player Name]=_player)
		displayFolder: Draft
		lineageTag: 33dc16ac-790c-48e2-9911-4728c0b55431

	measure DraftPlayerTeam =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
			return calculate(max(PlayersTable[Team City]),PlayersTable[Week]=1,PlayersTable[Player Name]=_player)&"  "&calculate(max(PlayerPointsStats[Position]),PlayerPointsStats[Week]=1,PlayerPointsStats[Player Name]=_player)
		displayFolder: Draft
		lineageTag: a0eb1c3e-4dc2-4f3a-ac5b-44d892ab05bf

	measure DraftName2 =
			
			var _team = SELECTEDVALUE(Draft[Team])
			var _round = SELECTEDVALUE(Draft[Round])
			return calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
		displayFolder: Draft
		lineageTag: 5f7c6234-b9aa-4f61-8c59-c1d1ec92f262

	measure DraftPic2 =
			
			var _team = SELECTEDVALUE(Draft[Team])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
			return calculate(max(PlayerPointsStats[headshot_url]),PlayerPointsStats[Player Name]=_player)
		displayFolder: Draft
		lineageTag: e4d799c3-2cb7-4606-983b-8c66a7cda7e9

	measure DraftPlayerPosition2 =
			
			var _team = SELECTEDVALUE(Draft[Team])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
			return calculate(max(Draft[Position]),Draft[Player]=_player)
		displayFolder: Draft
		lineageTag: fad5bb37-4d3c-42b3-8898-04fe3ac4afa7

	measure DraftPlayerTeam2 =
			
			var _team = SELECTEDVALUE(Draft[Team])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = calculate(max(Draft[Player]),Draft[Team]=_team,Draft[Round]=_round)
			return calculate(max(PlayersTable[Team City]),PlayersTable[Week]=1,PlayersTable[Player Name]=_player)&"  "&calculate(max(PlayerPointsStats[Position]),PlayerPointsStats[Week]=1,PlayerPointsStats[Player Name]=_player)
		displayFolder: Draft
		lineageTag: d32b7cfe-e48d-47f4-bf79-d06bd44d533f

	measure DraftTeam = ```
			SELECTEDVALUE(Draft[Team]) 
			```
		displayFolder: Draft
		lineageTag: aaaf9149-2697-4736-9b5d-eddb901a132d

	measure DraftRoundPick =
			
			var _round = SELECTEDVALUE(Draft[Round])
			var _pick = SELECTEDVALUE(Draft[Pick])
			return "Round: "&_round&" Pick: "&_pick
		displayFolder: Draft
		lineageTag: 78dff62d-645d-43ab-8fcc-49ddb36cb2b0

	measure DraftRound = SELECTEDVALUE(Draft[Round])
		formatString: 0
		displayFolder: Draft
		lineageTag: 54ead8fd-7ec2-45f5-acf2-d8bd14e61f7c

	measure DraftRoundText = "Round: "&[DraftRound]
		displayFolder: Draft
		lineageTag: 7e5099fc-e052-4634-8c9c-9461410c82df

	measure DraftPositionColor =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _round = SELECTEDVALUE(Draft[Round])
			var _player = [DraftName]
			var _position = calculate(max(UniquePlayers[Position]),UniquePlayers[Player Name]=_player)
			return _position
		displayFolder: Draft
		lineageTag: 64a7cf83-3177-4fd0-8cf0-eb09541a19d1

	measure QB# = calculate(COUNTROWS(Draft),Draft[Position]="QB",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: 3e835d6f-2590-4102-bd05-ee06ae35b2ec

	measure RB# = calculate(COUNTROWS(Draft),Draft[Position]="RB",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: bbe6a735-c35d-4a46-90db-9ab1744ac2bc

	measure WR# = calculate(COUNTROWS(Draft),Draft[Position]="WR",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: 02814e79-dc46-4464-a6af-87fce0d041cc

	measure K# = calculate(COUNTROWS(Draft),Draft[Position]="K",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: 4c19c30b-6cc8-4584-8bca-fcc596b1d18f

	measure D# = calculate(COUNTROWS(Draft),Draft[Position]="D/ST",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: 43500788-b30b-44bc-b2c4-e68db12bf6f2

	measure TE# = calculate(COUNTROWS(Draft),Draft[Position]="TE",Draft[Team]=SELECTEDVALUE(TeamsTable[Fantasy Name]),ALLEXCEPT(Draft,Draft[Team],Draft[Position]))
		formatString: 0
		displayFolder: Draft
		lineageTag: ec247aa7-33d6-45ae-be19-434db26d4aa9

	measure 'League Ranking Up/Down' = ```
			
			var _week = [Week]
			var _week2 = if(_week=1,_week,_week-1)
			
			var _team = max('Standings'[Team])
			var _current = CALCULATE(max('Standings'[League_Rank]),'Standings'[Team]=_team,'Standings'[Week]=_week)
			var _prior = CALCULATE(max('Standings'[League_Rank]),ALLEXCEPT('Standings','Standings'[Team],Weeks[Week]),'Standings'[Team]=_team,'Standings'[Week]=_week2,all(Weeks))
			var _variance = _current - _prior
			var _difference = SWITCH(TRUE(),
			                            // _week=1,"Same",
			                            _current - _prior = 0, "Same",
			                            _current - _prior > 0, "Down",
			                            _current - _prior < 0, "Up",
			                            "None"
			                            
			)
			return _variance
			```
		formatString: 0
		displayFolder: Scoreboard
		lineageTag: 6f51eb59-29dc-45f6-ac21-a8ab1908393a

	measure Record =
			
			var _week = [Week]
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			
			var _result = if(_wins,_wins,0)&"-"&if(_losses,_losses,0)&"-"&if(_tie,_tie,0)
			return _result
		displayFolder: Box Scores
		lineageTag: 712cd4b9-e785-494b-8b7f-d2afb33305fc

	measure PF =
			
			var _week = [Week]
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _pf = CALCULATE(sum('MatchupsTable'[Actual Points]),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Team]))
			
			return _pf
		displayFolder: Scoreboard
		lineageTag: c8d89d21-6004-4289-b1a5-46321672f9e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PA =
			
			var _week = [Week]
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _opponent = calculate(max(MatchupsTable[Opponent]),MatchupsTable[Week]=_week, MatchupsTable[Team]=_team)
			// SELECTEDVALUE('MatchupsTable'[Opponent])
			var _pf = CALCULATE(sum('MatchupsTable'[Actual Points]),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Opponent]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Opponent]))
			
			return _pf
		displayFolder: Scoreboard
		lineageTag: 4e678ef9-f411-44a4-801e-b08d9f0eda84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Win% =
			
			var _week = [Week]
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _calc = DIVIDE(_wins,_wins+_losses+_tie,0)
			return if(_calc,_calc,0)
		formatString: 0.000
		displayFolder: Scoreboard
		lineageTag: b8fb1196-e2cc-4b24-a299-438a01710761

	measure Streak =
			
			var _week = [Week]
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _result = CALCULATE(max(MatchupsTable[Result]),MatchupsTable[Week]=_week,MatchupsTable[Team]=_team)
			var _resultAbbr = LEFT(_result,1)
			var _streak = CALCULATE(max('MatchupsTable'[Week]),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]<>_result, 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			// var _streak = CALCULATE(max('MatchupsTable'[Week]),filter(MatchupsTable,'MatchupsTable'[Week]<=_week&&'MatchupsTable'[Result]<>_result&&'MatchupsTable'[Team]=_team))
			var _resultFinal = _resultAbbr&(_week-_streak)
			return _resultFinal
		displayFolder: Scoreboard
		lineageTag: 16ee94d2-d975-4a4e-8a2c-b96f31b7c074

	measure 'Net Pts' = [PF] - [PA]
		displayFolder: Scoreboard
		lineageTag: 02794213-a34d-45e5-bc91-379d52fa9c05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'League Ranking Up/Down ABS' = ```
			
			var _week = [Week]
			var _week2 = if(_week=1,_week,_week-1)
			
			var _team = max('Standings'[Team])
			var _current = CALCULATE(max('Standings'[League_Rank]),'Standings'[Team]=_team,'Standings'[Week]=_week)
			var _prior = CALCULATE(max('Standings'[League_Rank]),ALLEXCEPT('Standings','Standings'[Team],Weeks[Week]),'Standings'[Team]=_team,'Standings'[Week]=_week2,all(Weeks))
			var _variance = _current - _prior
			var _difference = SWITCH(TRUE(),
			                            // _week=1,"Same",
			                            _current - _prior = 0, "Same",
			                            _current - _prior > 0, "Down",
			                            _current - _prior < 0, "Up",
			                            "None"
			                            
			)
			return ABS(_variance)
			```
		formatString: 0
		displayFolder: Scoreboard
		lineageTag: 07f1a59c-8ba4-4b60-b380-b9ba771fb633

	measure 'Away Record' =
			
			var _week = [Week]-1
			var _team = [Home Name]
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			
			var _result = if(_wins,_wins,0)&"-"&if(_losses,_losses,0)&"-"&if(_tie,_tie,0)
			return _result
		displayFolder: Box Scores
		lineageTag: 16e52bf5-b9f3-4254-9f00-4e5b6284d772

	measure 'Scoreboard Home Points and arrow' = ```
			
			var _points = [Home Points]
			var _arrow = if([Home Points]>[Away Points],UNICHAR(9205),BLANK())
			return _arrow&_points
			
			```
		displayFolder: Box Scores
		lineageTag: f48490c9-4cc1-493b-90bd-764b5d4b0b24

	measure 'Scoreboard Away Points and arrow' = ```
			
			var _points = [Away Points]
			var _arrow = if([Home Points]<[Away Points],UNICHAR(9204),BLANK())
			return _points&_arrow
			
			```
		displayFolder: Box Scores
		lineageTag: 7dc20ca0-b652-4414-a9b2-39153c46a141

	measure 'home Record' =
			
			var _week = [Week]-1
			var _team = [Away Name]
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			
			var _result = if(_wins,_wins,0)&"-"&if(_losses,_losses,0)&"-"&if(_tie,_tie,0)
			return _result
		displayFolder: Box Scores
		lineageTag: ba6c9ad5-2d87-4afc-b266-60db1ffecac9

	measure 'Tornado Team 2 points' = -[Away Points]
		displayFolder: Box Scores
		lineageTag: d69367ec-ec6b-423d-b114-99cb5ff7b82f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Projected Points' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(MatchupsTable[Projected Points]),MatchupsTable[Week]=_wk)
			return _result
		displayFolder: Box Scores
		lineageTag: 9a34f6a6-6fda-4064-ad5f-386c4911f0fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Home plusOrMinus Text' =
			
			var _result = round([Home Points] - [Projected Points],2)
			var _sign = SWITCH(TRUE(),
			                    _result>0,"+",
			                    _result<0,"-"
			)
			return _sign&abs(_result)
		displayFolder: Box Scores
		lineageTag: 1884745e-1e3a-4e15-af99-50dfd4042c8c

	measure 'Offensive TDs' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute] IN {"TD Pass","TD Reception","TD Rush"})
			return _result
		displayFolder: Box Scores
		lineageTag: f2e7f0e3-c41c-48c2-818a-4eb81d981ec9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Offensive FGs' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, CONTAINSSTRING(PlayerPointsStats[Attribute],"FG Made"))
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 3e77c864-62a5-4fe4-be9b-de415ae9bb2b

	measure 'Offensive Fumbles' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute] IN {"Receiving Fumble","Rushing Fumble","Passer Fumble", "Interceptions Thrown"})
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 28b88044-ab56-47f6-b0dd-1ad1a00e8187

	measure 'Offensive Yards' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute] IN {"Receiving Yards","Rushing Yards","Passer Yards"})
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 1f94d87a-4b55-4f73-a996-65e22cb172f2

	measure 'Defensive TDs' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute]<>"TD Pass", PlayerPointsStats[Attribute]<>"TD Reception", PlayerPointsStats[Attribute]<>"TD Rush" ,CONTAINSSTRING(PlayerPointsStats[Attribute],"TD"))
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 39ab1d12-a47e-4cfe-ac55-0dc4c2cf5a46

	measure 'Defensive Interceptions' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute]="Each Interception")
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 0363239b-c631-4af8-8990-fff760392ab1

	measure 'Defensive Fumbles' =
			
			var _id = min(MatchupsTable[ID])
			var _wk = [Week]
			var _result = CALCULATE(sum(PlayerPointsStats[Value]),PlayerPointsStats[Week]=_wk, PlayerPointsStats[Attribute]="Each Fumble Recovered")
			return _result
		formatString: 0
		displayFolder: Box Scores
		lineageTag: 89415fd8-acea-4618-81fa-aa6dd3594754

	measure 'Away plusOrMinus Text' =
			
			var _result = round([Away Points] - [Projected Points],2)
			var _sign = SWITCH(TRUE(),
			                    _result>0,"+",
			                    _result<0,"-"
			)
			return _sign&abs(_result)
		displayFolder: Box Scores
		lineageTag: 0063cec5-08ce-4e21-881c-191f2ad8a6ac

	measure 'narrative expected or unexpected result' =
			
			var _wk = [Week]
			var _team = [Home Name]
			var _projected = CALCULATE(max(MatchupsTable[projected_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _actual = CALCULATE(max(MatchupsTable[actual_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _result = lower(CALCULATE(max(MatchupsTable[Result]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team))
			var _expected = SWITCH(TRUE(),
			                        (_projected<0 && _actual<0) || (_projected>0 && _actual>0), "expected ",
			                        "unexpected "
			)
			return _expected&_result
		displayFolder: Box Scores
		lineageTag: 23a66573-6aa2-4248-a93e-75408a89f4ae

	measure 'narrative actual result' =
			
			var _wk = [Week]
			var _team = [Home Name]
			var _projected = CALCULATE(max(MatchupsTable[projected_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _actual = CALCULATE(max(MatchupsTable[actual_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _result = if(_actual < 0,"lost","won")
			var _expected = SWITCH(TRUE(),
			                        (_projected<0 && _actual<0) || (_projected>0 && _actual>0), "expected ",
			                        "unexpected "
			)
			var _pts = if(_actual=1," point"," points")
			return _result&" by "&abs(_actual)&_pts
		displayFolder: Box Scores
		lineageTag: 66df18a8-127e-4b05-8f59-66463fd1e8ae

	measure 'narrative projected result' =
			
			var _wk = [Week]
			var _team = [Home Name]
			var _projected = CALCULATE(max(MatchupsTable[projected_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _actual = CALCULATE(max(MatchupsTable[actual_variance]),MatchupsTable[Week]=_wk, MatchupsTable[Team]=_team)
			var _result = if(_projected < 0,"lose","win")
			var _expected = SWITCH(TRUE(),
			                        (_projected<0 && _actual<0) || (_projected>0 && _actual>0), "expected ",
			                        "unexpected "
			)
			var _pts = if(_projected=1," point"," points")
			
			return _result&" by "&abs(_projected)&_pts
		displayFolder: Box Scores
		lineageTag: a8484c75-7117-46cc-9fb2-a5754560e231

	measure quadrantMin = CALCULATE(min(MatchupsTable[actual_variance]),all(MatchupsTable))-5
		displayFolder: Season Team Summary
		lineageTag: 0729e7a6-6b7c-4267-b9d3-cb2d085c5725

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure quadrantMax = CALCULATE(max(MatchupsTable[actual_variance]),all(MatchupsTable))+5
		displayFolder: Season Team Summary
		lineageTag: f0263f45-2779-4011-ba35-08304c015b16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'narrative categories home' =
			
			var _rushing = CALCULATE([Home Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _receiving = CALCULATE([Home Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _passing = CALCULATE([Home Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _kicking = CALCULATE([Home Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _d = CALCULATE([Home Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _differential = round(if(_rushing>0,_rushing,0) + if(_receiving>0,_receiving,0) + if(_passing>0,_passing,0) + if(_kicking>0,_kicking,0) + if(_d>0,_d,0),2)
			
			var _allcategories = SWITCH(TRUE(),
			                            _rushing>=0 && _receiving>=0 && _passing>=0 && _kicking>=0 && _d>=0, " led in all major point categories by a total of " & CONVERT(_differential,STRING) & " points",
			                             _differential=0, "None",
			                             BLANK()
			)
			
			var _partialcategories = if(_rushing>0,"rushing, ",BLANK()) & if(_receiving>0,"receiving, ",BLANK()) & if(_passing>0,"passing, ",BLANK()) & if(_kicking>0,"kicking, ",BLANK()) & if(_d>0,"defense, ",BLANK())
			
			var _partialCount = if(_rushing>0,1) + if(_receiving>0,1) + if(_passing>0,1) + if(_kicking>0,1) + if(_d>0,1)
			
			var _partialnew = SWITCH(TRUE(),
			                            _partialCount=1, SUBSTITUTE(_partialcategories,", "," "),
			                            _partialCount=2, SUBSTITUTE(SUBSTITUTE(_partialcategories,", "," and ",1),",",""),
			                            SUBSTITUTE(SUBSTITUTE(_partialcategories,", "," ",_partialCount),", ",", and ",_partialCount-1)
			)
			return SWITCH(TRUE(),
			                [Home Name]="BYE","This was a bye week matchup, so no points were scored.",
			                [Away Name]="BYE",BLANK(),
			                _allcategories<>"None" && NOT(ISBLANK(_allcategories)), [Home Name] & _allcategories,
			                _allcategories="None",BLANK(),
			                [Home Name] & " led in " & _partialnew & "by " & CONVERT(_differential,STRING) & " points"
			)
		displayFolder: Box Scores
		lineageTag: adfe65f7-a5ff-4065-a834-1635643a66ea

	measure 'narrative categories away' =
			
			var _rushing = CALCULATE([Away Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Home Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _receiving = CALCULATE([Away Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Home Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _passing = CALCULATE([Away Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Home Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _kicking = CALCULATE([Away Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Home Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _d = CALCULATE([Away Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Home Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			var _differential = round(if(_rushing>0,_rushing,0) + if(_receiving>0,_receiving,0) + if(_passing>0,_passing,0) + if(_kicking>0,_kicking,0) + if(_d>0,_d,0),2)
			
			var _allcategories = SWITCH(TRUE(),
			                            _rushing>=0 && _receiving>=0 && _passing>=0 && _kicking>=0 && _d>=0, " led in all major point categories by a total of " & CONVERT(_differential,STRING) & " points. ",
			                             _differential=0, "None",
			                             BLANK()
			)
			
			var _partialcategories = if(_rushing>0,"rushing, ",BLANK()) & if(_receiving>0,"receiving, ",BLANK()) & if(_passing>0,"passing, ",BLANK()) & if(_kicking>0,"kicking, ",BLANK()) & if(_d>0,"defense, ",BLANK())
			
			var _partialCount = if(_rushing>0,1) + if(_receiving>0,1) + if(_passing>0,1) + if(_kicking>0,1) + if(_d>0,1)
			
			var _partialnew = SWITCH(TRUE(),
			                            _partialCount=1, SUBSTITUTE(_partialcategories,", "," "),
			                            _partialCount=2, SUBSTITUTE(_partialcategories,", "," and "),
			                            SUBSTITUTE(SUBSTITUTE(_partialcategories,", "," ",_partialCount),", ",", and ",_partialCount-1)
			)
			
			return SWITCH(TRUE(),
			                [Away Name]="BYE","This was a bye week matchup, so no points were scored.",
			                [Home Name]="BYE",BLANK(),
			                ISBLANK([narrative categories home]),[Away Name] & _allcategories,
			                CONTAINSSTRING([narrative categories home],"all major"),".",
			                ", while " & [Away Name] & " led in " & _partialnew & "by " & CONVERT(_differential,STRING) & " points."
			)
		displayFolder: Box Scores
		lineageTag: 9644d51b-6641-466b-8f6d-03c9a292a0a2

	measure 'narrative categories combined' = [narrative categories home] & [narrative categories away]
		displayFolder: Box Scores
		lineageTag: c8d579b6-a1f6-4dc7-9f99-e8dda08b1a69

	measure 'narrative number of games' =
			
			var _home = [Home Name]
			var _away = [Away Name]
			
			var _games = CALCULATE(COUNTROWS(MatchupsTable),AND(MatchupsTable[Team]=_home,MatchupsTable[Opponent]=_away) && MatchupsTable[Week]<=SELECTEDVALUE(Weeks[Week]),ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent]))
			
			var _gamesText = CONVERT(_games,STRING)
			
			return SWITCH(TRUE(),
			                _games = 11,"11th ",
			                _games = 12,"12th ",
			                _games = 13,"13th ",
			                MOD(_games,10)=1,_gamesText & "st ",
			                MOD(_games,10)=2,_gamesText & "nd ",
			                MOD(_games,10)=3,_gamesText & "rd ",
			                _gamesText & "th "
			
			)
		displayFolder: Box Scores
		lineageTag: abf62e3d-8285-4bc6-a2f9-e02d5c13f012

	measure 'narrative series' =
			
			var _home = [Home Name]
			var _away = [Away Name]
			var _week = [Week]
			
			var _homeWins = CALCULATE(COUNTROWS(MatchupsTable),AND(MatchupsTable[Team]=_home,MatchupsTable[Opponent]=_away), MatchupsTable[Week]<=_week && MatchupsTable[Result]="Win",ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent],MatchupsTable[Result]))
			
			var _awayWins = CALCULATE(COUNTROWS(MatchupsTable),AND(MatchupsTable[Team]=_away,MatchupsTable[Opponent]=_home), MatchupsTable[Week]<=_week && MatchupsTable[Result]="Win",ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent],MatchupsTable[Result]))
			
			var _ties = CALCULATE(COUNTROWS(MatchupsTable),AND(MatchupsTable[Team]=_away,MatchupsTable[Opponent]=_home), MatchupsTable[Week]<=_week && MatchupsTable[Result]="Tie",ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent],MatchupsTable[Result]))
			
			var _homeNum = if(_homeWins,_homeWins,0)
			var _awayNum = if(_awayWins,_awayWins,0)
			var _tieNum = if(_ties,_ties,0)
			
			return SWITCH(TRUE(),
			                _homeWins>_awayWins,_home & " leads the series " & CONVERT(_homeNum,STRING) & "-" & CONVERT(_awayNum,STRING) & "-" & CONVERT(_tieNum,STRING) & ".",
			                _homeWins<_awayWins,_away & " leads the series " & CONVERT(_awayNum,STRING) & "-" & CONVERT(_homeNum,STRING) & "-" & CONVERT(_tieNum,STRING) & ".",
			                "the series is tied " & CONVERT(_awayWins,STRING) & "-" & CONVERT(_homeNum,STRING) & "-" & CONVERT(_tieNum,STRING) & "."
			)
		displayFolder: Box Scores
		lineageTag: 87953c18-e96b-4412-8208-291d5d8a532c

	measure 'narrative playoff' =
			
			var _home = [Home Name]
			var _away = [Away Name]
			var _week = [Week]
			
			var _isplayoff = if(CALCULATE(max(MatchupsTable[matchup_type]),AND(MatchupsTable[Team]=_home,MatchupsTable[Opponent]=_away) && MatchupsTable[Week]=_week,ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent]))="WINNERS_BRACKET",1,0)
			
			var _winner = if(CALCULATE(max(MatchupsTable[Result]),AND(MatchupsTable[Team]=_home,MatchupsTable[Opponent]=_away), MatchupsTable[Week]=_week,ALLEXCEPT(MatchupsTable,MatchupsTable[Week],MatchupsTable[Team],MatchupsTable[Opponent]))="Win",_home,_away)
			
			var _round = SWITCH(TRUE(),
			                    SELECTEDVALUE(Weeks[Week])=15," 1st ",
			                    SELECTEDVALUE(Weeks[Week])=15," 2nd "
			)
			
			return SWITCH(TRUE(),
			                _isplayoff=0," ",
			                _away = "BYE", "This was a playoff bye week for " & _home & ", who now advances to the second round.",
			                SELECTEDVALUE(Weeks[Week])=17, "This was the championship game, congrats to " & _winner & " on their league victory this season!",
			                "This was a playoff game in the" & _round & "round, and with " & _winner & "'s victory they advance to the next round."
			)
		displayFolder: Box Scores
		lineageTag: 2b8fb810-e137-45b6-8629-424a1b28fe2e

	measure 'Point Performance Summary' = max(MatchupsTable[Actual Points]) - max(MatchupsTable[Projected Points])
		displayFolder: Season Team Summary
		lineageTag: a4419258-70e4-4b82-8f97-21b9159124fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelectedTeam = SELECTEDVALUE(MatchupsTable[Team])
		displayFolder: .General
		lineageTag: 1bcd75af-adca-4353-97ad-067e27a1eeb4

	measure 'Close games' =
			
			var _team = [SelectedTeam]
			return CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team]=_team,ABS(MatchupsTable[actual_variance])<=10)
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 0a032aff-e851-4bf3-a34d-ba3ca4ad21f6

	measure Blowouts =
			
			var _team = [SelectedTeam]
			return CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team]=_team,ABS(MatchupsTable[actual_variance])>=30)
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 71f22516-a0c8-4cb8-9cff-fd74bdfbb680

	measure 'Close or Blowout Record' =
			
			var _team = [SelectedTeam]
			var _blow = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team]=_team,ABS(MatchupsTable[actual_variance])>=30 || ABS(MatchupsTable[actual_variance])<=10)
			var _blowWins = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team]=_team,MatchupsTable[Result]="Win",ABS(MatchupsTable[actual_variance])>=30 || ABS(MatchupsTable[actual_variance])<=10)
			return CONVERT(_blowWins,STRING) & " out of " & CONVERT(_blow,STRING)
		displayFolder: Season Team Summary
		lineageTag: 6e703723-7d9e-4052-8e57-072b1337f23e

	measure 'Forecast Comparison' =
			
			var _team = [SelectedTeam]
			// var _projectedwins = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team] = _team,MatchupsTable[projected_variance]>0)
			// var _actualwins = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team] = _team,MatchupsTable[projected_variance]>0,MatchupsTable[Result]="Win")
			var _expectedResults = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team] = _team,NOT(CONTAINSSTRING(MatchupsTable[Legend],"Un")))
			var _totalresults = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team] = _team)
			var _result = ROUND(100*DIVIDE(_expectedResults,_totalresults,0),0)
			return _result
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: e48f45fe-ae21-4db0-a5be-954832805541

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Forecast comparison text' =
			
			SWITCH(TRUE(),
			        [Forecast Comparison]>=40 && [Forecast Comparison]<=60, "neutrally",
			        [Forecast Comparison]>60,"well",
			        [Forecast Comparison]<40,"poorly"
			)
		displayFolder: Season Team Summary
		lineageTag: 147c5a21-1aa8-473c-bd28-82ee6f0f10f4

	measure 'Stolen Games' =
			
			var _team = [SelectedTeam]
			var _wins = CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Team] = _team,MatchupsTable[projected_variance]<0,MatchupsTable[Result]="Win")
			return SWITCH(TRUE(),
			                _wins=1, _wins & " game",
			                _wins=0,"no games",
			                _wins & " games"
			)
		displayFolder: Season Team Summary
		lineageTag: c8dfce30-9e5f-4178-a022-05199baa1276

	measure 'Performance Summary Value' = ```
			
			var _value = round(AVERAGEX(MatchupsTable,MatchupsTable[Actual Points] - MatchupsTable[Projected Points]),2)
			var _result = SWITCH(TRUE(),
			                        _value=0, "scored their expected number of",
			                        _value>0, "overperformed by " & abs(_value),
			                        "underperformed by " & abs(_value)
			)
			return _result 
			```
		displayFolder: Season Team Summary
		lineageTag: f9b28137-24e1-4ea9-ad0b-ec0386dbbef2

	measure 'Power Ranking Start' = CALCULATE(max('Power Rankings'[Rank]),'Power Rankings'[Week]=1)
		formatString: 0
		displayFolder: Power Ranking Chart
		lineageTag: 0ebbf1df-fecb-4d72-83e6-af4e5858532b

	measure 'Power Ranking End' =
			
			var _wk = CALCULATE(max(PlayerPointsStats[Week]),ALL(PlayerPointsStats))
			var _result = CALCULATE(max('Power Rankings'[Rank]),'Power Rankings'[Week]=_wk)
			return _result
		formatString: 0
		displayFolder: Power Ranking Chart
		lineageTag: 432ad601-fa3c-466d-92b8-412d8f14a125

	measure 'Power Ranking Color Indicator' = [Power Ranking End] - [Power Ranking Start]
		formatString: 0
		displayFolder: Power Ranking Chart
		lineageTag: 5cd6c825-8e13-440c-9479-35568f8fadd3

	measure 'Top Performer 1' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _player = CALCULATE(max(TopPerformers[Name Abbrev]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=1)
			return _player
		displayFolder: Box Scores
		lineageTag: c4255327-4854-4e22-a6e7-f3ddafeb5720

	measure 'Top Performer 2' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _player = CALCULATE(max(TopPerformers[Name Abbrev]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=2)
			return _player
		displayFolder: Box Scores
		lineageTag: c0ae7ed9-0e09-4b10-8108-5b43ad048b43

	measure 'Top Performer 3' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _player = CALCULATE(max(TopPerformers[Name Abbrev]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=3)
			return _player
		displayFolder: Box Scores
		lineageTag: fbf73f5a-8643-43c1-83a8-248b135b1bf2

	measure 'Top Performer 1 Points' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _points = CALCULATE(max(TopPerformers[Actual]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=1)
			return  CONVERT(_points,STRING) & " pts"
		displayFolder: Box Scores
		lineageTag: d99415c7-d873-480f-92dc-5bf3b7b68253

	measure 'Top Performer 2 Points' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _points = CALCULATE(max(TopPerformers[Actual]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=2)
			return  CONVERT(_points,STRING) & " pts"
		displayFolder: Box Scores
		lineageTag: a3632b5c-24ad-4836-9b04-cc5eb0bf30dd

	measure 'Top Performer 3 Points' =
			
			var _week = [Week]
			var _team = SWITCH(TRUE(),
			                    SELECTEDVALUE(MatchupsTable[Home_Or_Away])="Home",[Home Name],[Away Name])
			var _points = CALCULATE(max(TopPerformers[Actual]),TopPerformers[FantasyTeam]=_team,TopPerformers[Week]=_week,TopPerformers[Rank]=3)
			return  CONVERT(_points,STRING) & " pts"
		displayFolder: Box Scores
		lineageTag: 70f43dde-f1f7-425d-a9bd-fcbea424a419

	measure 'Season Record' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			
			var _result = if(_wins,_wins,0)&"-"&if(_losses,_losses,0)&"-"&if(_tie,_tie,0)
			return _result
		displayFolder: Season Team Summary
		lineageTag: cedd964d-14c6-41cf-9f5a-b35087cc8654

	measure 'Season Win %' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _wins = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Win", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _losses = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Loss", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[result],'MatchupsTable'[Team]))
			var _tie = CALCULATE(COUNTROWS('MatchupsTable'),'MatchupsTable'[Result]="Tie", 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			
			var _result = DIVIDE(_wins,_wins+_losses+_tie,0)
			return _result
		formatString: 0%;-0%;0%
		displayFolder: Season Team Summary
		lineageTag: 2cea6188-a63f-4a26-be2a-ec421b841531

	measure 'Final League Standing' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _wk = CALCULATE(max(PlayerPointsStats[Week]),all(PlayerPointsStats))
			var _ranking = CALCULATE(max('Standings'[League_Rank]),'Standings'[Team]=_team,'Standings'[Week]=_wk)
			return _ranking
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 6b427b28-6d05-4cd3-b08c-07aceea2adfc

	measure 'Final Division Standing' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _wk = CALCULATE(max(PlayerPointsStats[Week]),all(PlayerPointsStats))
			var _ranking = CALCULATE(max('Standings'[Division_Rank]),'Standings'[Team]=_team,'Standings'[Week]=_wk)
			return _ranking
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: fa5eead4-d864-49cf-92ff-f854edb69f71

	measure 'Final Streak' =
			
			var _resultAbbr = UPPER(LEFT([Final Streak WinLoss],1))
			var _resultFinal = _resultAbbr&([Final Streak Number])
			return _resultFinal
		displayFolder: Season Team Summary
		lineageTag: 98511ec3-7eeb-4eb0-bc71-0a48e0a6ed9f

	measure 'Final Power Ranking' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _wk = CALCULATE(max(PlayerPointsStats[Week]),all(PlayerPointsStats))
			var _ranking = CALCULATE(max('Power Rankings'[Rank]),'Power Rankings'[Team]=_team,'Power Rankings'[Week]=_wk)
			return _ranking
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 831836f0-3046-4fb3-84a3-80e76e5a2494

	measure 'Close Or Blowout Indicator' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _blow = SWITCH(TRUE(),
			                    ABS(CALCULATE(max(MatchupsTable[actual_variance]),MatchupsTable[Team]=_team))>=30,"Blowout",
			                    ABS(CALCULATE(max(MatchupsTable[actual_variance]),MatchupsTable[Team]=_team))<=10,"Close Game",
			                    "--"
			                    )
			return _blow
		displayFolder: Season Team Summary
		lineageTag: 104cf399-a297-43e7-a399-5e3614804159

	measure 'Expected Wins' = ```
			CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Legend]="Expected Win") 
			```
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: f8bd58d6-decf-4639-b5c4-90f7edb1a019

	measure 'Expected Losses' = ```
			CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Legend]="Expected Loss") 
			```
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 2c740487-5075-441c-ab55-3f30aaaf7717

	measure 'Unexpected Wins' = ```
			CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Legend]="Unexpected Win") 
			```
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 6395451d-0941-4d13-8d81-33a8cb5ee936

	measure 'Unexpected Losses' = ```
			CALCULATE(COUNTROWS(MatchupsTable),MatchupsTable[Legend]="Unexpected Loss") 
			```
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 80478f54-9fe8-4326-886e-42701cc5078c

	measure 'Expected Win Margin' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			return ROUND(CALCULATE(AVERAGE(MatchupsTable[actual_variance]),MatchupsTable[Legend] = "Expected Win",MatchupsTable[Team]=_team),0)
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 2344c392-e90d-4d84-ae98-05c31c84cab7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Expected Loss Margin' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			return abs(ROUND(CALCULATE(AVERAGE(MatchupsTable[actual_variance]),MatchupsTable[Legend] = "Expected Loss",MatchupsTable[Team]=_team),0))
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 6dfbe8a0-6946-4a94-b16b-af6c998f734c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Unexpected Win Margin' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			return ROUND(CALCULATE(AVERAGE(MatchupsTable[actual_variance]),MatchupsTable[Legend] = "Unexpected Win",MatchupsTable[Team]=_team),0)
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 1cf2bd3c-c614-44f2-8e87-c2f73c2d6f5a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Unexpected Loss Margin' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			return abs(ROUND(CALCULATE(AVERAGE(MatchupsTable[actual_variance]),MatchupsTable[Legend] = "Unexpected Loss",MatchupsTable[Team]=_team),0))
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: f59e02d6-031b-4136-a467-7dd78906e47e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Final Streak WinLoss' =
			
			var _week = CALCULATE(max(PlayerPointsStats[Week]),all(PlayerPointsStats))
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _result = Lower(CALCULATE(max(MatchupsTable[Result]),MatchupsTable[Week]=_week,MatchupsTable[Team]=_team))
			return SWITCH(TRUE(),_result="loss","losing",_result)
		displayFolder: Season Team Summary
		lineageTag: 46808c06-71af-4092-8aa1-5c563eca7b88

	measure 'Final Streak Number' =
			
			var _week = CALCULATE(max(PlayerPointsStats[Week]),all(PlayerPointsStats))
			var _team = SELECTEDVALUE('TeamsTable'[Fantasy Name])
			var _result = CALCULATE(max(MatchupsTable[Result]),MatchupsTable[Week]=_week,MatchupsTable[Team]=_team)
			var _streak = CALCULATE(max('MatchupsTable'[Week]),'MatchupsTable'[Week]<=_week,'MatchupsTable'[Result]<>_result, 'MatchupsTable'[Team]=_team,ALLEXCEPT('MatchupsTable','MatchupsTable'[Week],'MatchupsTable'[Result],'MatchupsTable'[Team]))
			return _week-_streak
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: f3893d6d-388e-4a33-a03b-586b4fc94323

	measure 'season summary league rank text' =
			
			var _team = [SelectedTeam]
			
			var _value = [Final League Standing]
			
			var _gamesText = CONVERT(_value,STRING)
			
			return SWITCH(TRUE(),
			                _value = 11,"11th ",
			                _value = 12,"12th ",
			                _value = 13,"13th ",
			                MOD(_value,10)=1,_gamesText & "st ",
			                MOD(_value,10)=2,_gamesText & "nd ",
			                MOD(_value,10)=3,_gamesText & "rd ",
			                _gamesText & "th "
			
			)
		displayFolder: Season Team Summary
		lineageTag: fff28793-28e6-402e-b304-ac48c5b573f8

	measure 'Initial Power Ranking' =
			
			var _team = SELECTEDVALUE(TeamsTable[Fantasy Name])
			var _ranking = CALCULATE(max('Power Rankings'[Rank]),'Power Rankings'[Team]=_team,'Power Rankings'[Week]=1)
			return _ranking
		formatString: 0
		displayFolder: Season Team Summary
		lineageTag: 8d93848a-a6bb-4ed8-bdb1-e7739f5e8a2c

	measure 'Power Ranking Difference' =
			
			var _diff = [Initial Power Ranking] - [Final Power Ranking]
			var _slot = SWITCH(TRUE(),_diff=1,"slot","slots")
			return SWITCH(TRUE(),
			                _diff=0, "remained at the same power ranking slot of "&[Final Power Ranking],
			                _diff>0,"improved in the power rankings by "&abs(_diff)& " "&_slot&" from "&[Initial Power Ranking]&" to "&[Final Power Ranking],
			                "regressed in the power rankings by "&abs(_diff)& " "&_slot&" from "&[Initial Power Ranking]&" to "&[Final Power Ranking]
			)
		displayFolder: Season Team Summary
		lineageTag: afb62414-a1de-4c62-9c91-2450c2d979cd

	measure 'Close Game Text' =
			SWITCH(TRUE(),
			                            [Close games]=1,"game",
			                            "games"
			)
		displayFolder: Season Team Summary
		lineageTag: 2d0d0b45-ed5e-4827-a2c6-8ee922bc0b49

	measure 'Blowout Games text' = SWITCH(TRUE(),[Blowouts]=1,"blowout","blowouts")
		displayFolder: Season Team Summary
		lineageTag: 6727dd7d-5494-433c-9b14-22c98fb00008

	measure 'Category Rankings Text' =
			
			var _team = [SelectedTeam]
			
			var _rushing = CALCULATE(max(SpiderChart[Condensed Rank]),SpiderChart[FantasyTeam]=_team,SpiderChart[Category]="Rushing")
			var _receiving = CALCULATE(max(SpiderChart[Condensed Rank]),SpiderChart[FantasyTeam]=_team,SpiderChart[Category]="Receiving")
			var _passing = CALCULATE(max(SpiderChart[Condensed Rank]),SpiderChart[FantasyTeam]=_team,SpiderChart[Category]="Passing")
			var _kicking = CALCULATE(max(SpiderChart[Condensed Rank]),SpiderChart[FantasyTeam]=_team,SpiderChart[Category]="Kicking")
			var _d = CALCULATE(max(SpiderChart[Condensed Rank]),SpiderChart[FantasyTeam]=_team,SpiderChart[Category]="D/ST")
			
			var _numberOver = CALCULATE(COUNTROWS(SpiderChart),SpiderChart[FantasyTeam]=_team,SpiderChart[Condensed Rank]>=5)
			var _numberUnder = CALCULATE(COUNTROWS(SpiderChart),SpiderChart[FantasyTeam]=_team,SpiderChart[Condensed Rank]<=2)
			var _numberMid = CALCULATE(COUNTROWS(SpiderChart),SpiderChart[FantasyTeam]=_team,SpiderChart[Condensed Rank]>2,SpiderChart[Condensed Rank]<5)
			
			var _partialOver = if(_rushing>4,"rushing, ",BLANK()) & if(_receiving>4,"receiving, ",BLANK()) & if(_passing>4,"passing, ",BLANK()) & if(_kicking>4,"kicking, ",BLANK()) & if(_d>4,"defense, ",BLANK())
			var _partialUnder = if(_rushing<3,"rushing, ",BLANK()) & if(_receiving<3,"receiving, ",BLANK()) & if(_passing<3,"passing, ",BLANK()) & if(_kicking<3,"kicking, ",BLANK()) & if(_d<3,"defense, ",BLANK())
			var _partialMid = if(_rushing=3||_rushing=4,"rushing, ",BLANK()) & if(_receiving=3||_receiving=4,"receiving, ",BLANK()) & if(_passing=3||_passing=4,"passing, ",BLANK()) & if(_kicking=3||_kicking=4,"kicking, ",BLANK()) & if(_d=3||_d=4,"defense, ",BLANK())
			
			var _partialOverCount = if(_rushing>4,1) + if(_receiving>4,1) + if(_passing>4,1) + if(_kicking>4,1) + if(_d>4,1)
			var _partialOverText = SWITCH(TRUE(),
			                            _partialOverCount=1, SUBSTITUTE(_partialOver,", "," "),
			                            _partialOverCount=2, SUBSTITUTE(SUBSTITUTE(_partialOver,", "," and ",1),",",""),
			                            SUBSTITUTE(SUBSTITUTE(_partialOver,", "," ",_partialOverCount),", ",", and ",_partialOverCount-1)
			)
			
			var _partialUnderCount = if(_rushing<3,1) + if(_receiving<3,1) + if(_passing<3,1) + if(_kicking<3,1) + if(_d<3,1)
			var _partialUnderText = SWITCH(TRUE(),
			                            _partialUnderCount=1, SUBSTITUTE(_partialUnder,", "," "),
			                            _partialUnderCount=2, SUBSTITUTE(SUBSTITUTE(_partialUnder,", "," and ",1),",",""),
			                            SUBSTITUTE(SUBSTITUTE(_partialUnder,", "," ",_partialUnderCount),", ",", and ",_partialUnderCount-1)
			)
			
			var _partialMidCount = if(_rushing=3||_rushing=4,1) + if(_receiving=3||_receiving=4,1) + if(_passing=3||_passing=4,1) + if(_kicking=3||_kicking=4,1) + if(_d=3||_d=4,1)
			var _partialMidText = SWITCH(TRUE(),
			                            _partialMidCount=1, SUBSTITUTE(_partialMid,", "," "),
			                            _partialMidCount=2, SUBSTITUTE(SUBSTITUTE(_partialMid,", "," and ",1),",",""),
			                            SUBSTITUTE(SUBSTITUTE(_partialMid,", "," ",_partialMidCount),", ",", and ",_partialMidCount-1)
			)
			
			return SWITCH(TRUE(),
			                _numberOver=5," above average in all five areas",
			                _numberUnder=5," below average in all five areas",
			                _partialOverCount>1 && _partialUnderCount>1 && _partialMidCount>1
			)
			
			// var _rushing = CALCULATE([Home Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Rushing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			// var _receiving = CALCULATE([Home Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Receiving",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			// var _passing = CALCULATE([Home Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Passing",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			// var _kicking = CALCULATE([Home Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="Kicking",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			// var _d = CALCULATE([Home Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE"))) - CALCULATE([Away Points],PointsMap[Category]="D/ST",NOT(CONTAINSSTRING(PlayerPointsStats[Lineup Slot],"BE")))
			
			// var _differential = round(if(_rushing>0,_rushing,0) + if(_receiving>0,_receiving,0) + if(_passing>0,_passing,0) + if(_kicking>0,_kicking,0) + if(_d>0,_d,0),2)
			
			// var _allcategories = SWITCH(TRUE(),
			//                             _rushing>=0 && _receiving>=0 && _passing>=0 && _kicking>=0 && _d>=0, " led in all major point categories by a total of " & CONVERT(_differential,STRING) & " points",
			//                              _differential=0, "None",
			//                              BLANK()
			// )
			
			// var _partialcategories = if(_rushing>0,"rushing, ",BLANK()) & if(_receiving>0,"receiving, ",BLANK()) & if(_passing>0,"passing, ",BLANK()) & if(_kicking>0,"kicking, ",BLANK()) & if(_d>0,"defense, ",BLANK())
			
			// var _partialCount = if(_rushing>0,1) + if(_receiving>0,1) + if(_passing>0,1) + if(_kicking>0,1) + if(_d>0,1)
			
			// var _partialnew = SWITCH(TRUE(),
			//                             _partialCount=1, SUBSTITUTE(_partialcategories,", "," "),
			//                             _partialCount=2, SUBSTITUTE(SUBSTITUTE(_partialcategories,", "," and ",1),",",""),
			//                             SUBSTITUTE(SUBSTITUTE(_partialcategories,", "," ",_partialCount),", ",", and ",_partialCount-1)
			// )
			// return SWITCH(TRUE(),
			//                 [Home Name]="BYE","This was a bye week matchup, so no points were scored.",
			//                 [Away Name]="BYE",BLANK(),
			//                 _allcategories<>"None" && NOT(ISBLANK(_allcategories)), [Home Name] & _allcategories,
			//                 _allcategories="None",BLANK(),
			//                 [Home Name] & " led in " & _partialnew & "by " & CONVERT(_differential,STRING) & " points"
			// )
		displayFolder: Season Team Summary
		lineageTag: 2f8b8cbd-92fe-4975-a279-83aefca381a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Week = SELECTEDVALUE(Weeks[Week])
		formatString: 0
		displayFolder: .General
		lineageTag: 43072598-3838-4706-9bb5-b851d4c9baf7

	measure 'Playoff Home' = [Home Name] & " " & [Home Points]
		lineageTag: 29b5f2ce-1e5f-43c6-b081-fc3acec84df5

	measure 'Playoff Away' = [Away Name] & " " & [Away Points]
		lineageTag: e1c6104a-7c6b-4498-bc81-5492048dd1ea

	partition *Measures = m
		mode: import
		source =
				let
				    Source = "",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"*Measures"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Text

