table MatchupsTable
	lineageTag: 953f438f-86d1-4d5a-88c2-daedc552e940

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 41b2b81b-7573-4733-9ad5-d326f255a711
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: c5a07824-f188-4461-b30c-9d42ca6fced5
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 58d5510e-4bba-4dca-9016-778b358f9bfd
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Opponent
		dataType: string
		lineageTag: 1bff98fb-0693-4209-b0dc-f33fe0f21a91
		summarizeBy: none
		sourceColumn: Opponent

		annotation SummarizationSetBy = Automatic

	column 'Actual Points'
		dataType: double
		lineageTag: e21cb466-a961-47d4-9bd0-dcd5fdbc8a4c
		summarizeBy: sum
		sourceColumn: Actual Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Result
		dataType: string
		lineageTag: a00feb74-55d7-41ad-a22a-5bb8c7f73fb7
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column 'Matchup Header'
		dataType: string
		lineageTag: 7f8ed995-0258-471a-bd5d-184553176213
		summarizeBy: none
		sourceColumn: Matchup Header

		annotation SummarizationSetBy = Automatic

	column Number
		dataType: int64
		formatString: 0
		lineageTag: 1f194657-9301-41b9-863b-067b017043ac
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column MatchupKey
		dataType: string
		lineageTag: feddec63-64ea-4d10-b4f4-47d317408928
		summarizeBy: none
		sourceColumn: MatchupKey

		annotation SummarizationSetBy = Automatic

	column WeeklyMatchupID
		dataType: int64
		formatString: 0
		lineageTag: 1ba6ae8f-b1d2-4718-88be-d70bcccd95f7
		summarizeBy: count
		sourceColumn: WeeklyMatchupID

		annotation SummarizationSetBy = Automatic

	column Home_Or_Away
		dataType: string
		lineageTag: facfa2ac-a3ca-45a3-a9fa-b08108f65177
		summarizeBy: none
		sourceColumn: Home_Or_Away

		annotation SummarizationSetBy = Automatic

	column 'Projected Points'
		dataType: double
		lineageTag: 6cf18baa-3367-44db-9f18-e499e9dec9fa
		summarizeBy: sum
		sourceColumn: Projected Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column matchup_type
		dataType: string
		lineageTag: 3af64dbc-f109-4640-bad8-17b95c261c93
		summarizeBy: none
		sourceColumn: matchup_type

		annotation SummarizationSetBy = Automatic

	column projected_variance
		dataType: double
		lineageTag: 57b014ce-d76d-43b1-8fd2-562ced25b4ad
		summarizeBy: sum
		sourceColumn: projected_variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column actual_variance
		dataType: double
		lineageTag: 4243c220-5aff-4b85-a71b-f2304b3fa91d
		summarizeBy: sum
		sourceColumn: actual_variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Matchup Header Abbrev'
		dataType: string
		lineageTag: cd4fed78-15b0-48f8-bc0d-b359392a2bd9
		summarizeBy: none
		sourceColumn: Matchup Header Abbrev

		annotation SummarizationSetBy = Automatic

	column Legend
		dataType: string
		lineageTag: ad0a57e1-06c4-4aa8-8272-408ba54de4c8
		summarizeBy: none
		sourceColumn: Legend

		annotation SummarizationSetBy = Automatic

	partition MatchupsTable = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\matchups.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Team", type text}, {"Opponent", type text}, {"Week", Int64.Type}, {"Home_Or_Away", type text}, {"Projected Points", type number}, {"Actual Points", type number}, {"matchup_type", type text}, {"projected_variance", type number}, {"actual_variance", type number}, {"Matchup Header", type text}, {"Result", type text}, {"Number", Int64.Type}, {"MatchupKey", type text}, {"WeeklyMatchupID", Int64.Type}, {"ID", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Matchup Header", "Matchup Header Abbrev"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","Sith Happens","SH",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Compile and Conquer","CNC",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Kuppenheimer","THAr",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","A's Astounding Team","AAT",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Drafted by AI","JST",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Baby Back Gibbs","JG",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Mighty Rubber Ducks","MRD",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Bring the heat","BT",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Magic M","MM",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Apex Predators","AP",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","K's Deluxe Team","KDT",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","Boomer Sooners","OU",Replacer.ReplaceText,{"Matchup Header Abbrev"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value11", "Legend", each if [projected_variance]>0 and [actual_variance]<0 then "Unexpected Loss" else if [projected_variance]<0 and [actual_variance]>0 then "Unexpected Win" else if [projected_variance]>0 and [actual_variance]>0 then "Expected Win" else "Expected Loss")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

