table 'New Matchups'
	lineageTag: a79045f4-9fa0-45ca-8324-750033029aa0

	column Team
		dataType: string
		lineageTag: 41716756-72c2-49a3-a482-95f5ae686f9f
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 7ad51654-3cbb-4cf9-acc9-6e1f47a85646
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Home_Or_Away
		dataType: string
		lineageTag: cb0e17dc-88ea-436c-85d6-d0ced0632bae
		summarizeBy: none
		sourceColumn: Home_Or_Away

		annotation SummarizationSetBy = Automatic

	column matchup_type
		dataType: string
		lineageTag: a3939906-c24a-487b-976c-5294786ad904
		summarizeBy: none
		sourceColumn: matchup_type

		annotation SummarizationSetBy = Automatic

	column projected_variance
		dataType: double
		lineageTag: 82fa7e04-180d-4f72-bfcd-15a7dd04468e
		summarizeBy: sum
		sourceColumn: projected_variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column actual_variance
		dataType: double
		lineageTag: ab5dd87f-27dd-443f-a73e-e47e2a6cda6f
		summarizeBy: sum
		sourceColumn: actual_variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Opponent
		dataType: string
		lineageTag: 6d26644b-969f-4a03-9cd9-5cea31291f62
		summarizeBy: none
		sourceColumn: Opponent

		annotation SummarizationSetBy = Automatic

	column 'Projected Points'
		dataType: double
		lineageTag: 68c81d4c-7d13-4000-a5cd-7ccd0911f88a
		summarizeBy: sum
		sourceColumn: Projected Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Points'
		dataType: double
		lineageTag: eaf4014f-2f6f-4d48-be47-70c20703d383
		summarizeBy: sum
		sourceColumn: Actual Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Matchup Header'
		dataType: string
		lineageTag: fb80c54b-3698-4691-b73b-6a007d79aff7
		summarizeBy: none
		sourceColumn: Matchup Header

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 604caf9f-f7fa-4958-a4d5-36a5f9662493
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column Number
		dataType: int64
		formatString: 0
		lineageTag: b7ea3273-ccdb-4865-b40c-e97a56b101f4
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column MatchupKey
		dataType: string
		lineageTag: 728e1369-25f1-407b-a2d7-9c60c194961d
		summarizeBy: none
		sourceColumn: MatchupKey

		annotation SummarizationSetBy = Automatic

	column WeeklyMatchupID
		dataType: int64
		formatString: 0
		lineageTag: 152c37b5-d1bf-47f5-a511-49094ea247de
		summarizeBy: count
		sourceColumn: WeeklyMatchupID

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: f5404bdd-51d5-4f0d-b11e-717adc5846e4
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition 'New Matchups' = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\matchups.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Team", type any}, {"Week", Int64.Type}, {"Home_Or_Away", type text}, {"matchup_type", type text}, {"projected_variance", type number}, {"actual_variance", type number}, {"Opponent", type text}, {"Actual Points", type number}, {"Projected Points", type number}, {"Matchup Header", type text}, {"Result", type text}, {"Number", Int64.Type}, {"MatchupKey", type text}, {"WeeklyMatchupID", Int64.Type}, {"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

