table PlayersTable
	lineageTag: 6af93a31-e711-4307-8e27-270955939562

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 2afb4c31-1e4c-47c5-a7dc-c8d379e28e6f
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column 'Player Name'
		dataType: string
		lineageTag: 753986c1-0a32-4491-aca6-d08e87e1054d
		summarizeBy: none
		sourceColumn: Player Name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0ba38747-03ff-40ff-9968-b749169e0179
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column MatchupKey
		dataType: string
		lineageTag: 9ce61e8a-a4dc-4a62-8d4f-6332da3910e1
		summarizeBy: none
		sourceColumn: MatchupKey

		annotation SummarizationSetBy = Automatic

	column PlayerKey
		dataType: string
		lineageTag: 42eb47e3-fc8b-4e68-b44b-bfed58819e61
		summarizeBy: none
		sourceColumn: PlayerKey

		annotation SummarizationSetBy = Automatic

	column 'Fantasy Name'
		dataType: string
		lineageTag: 20f728e0-c0a0-42fc-8a5f-c5f4e3c385d4
		summarizeBy: none
		sourceColumn: Fantasy Name

		annotation SummarizationSetBy = Automatic

	column 'Team City'
		dataType: string
		lineageTag: 15c64090-1e8f-40db-ae4d-87ca0ab8668d
		summarizeBy: none
		sourceColumn: Team City

		annotation SummarizationSetBy = Automatic

	column 'Lineup Slot'
		dataType: string
		lineageTag: 44cad283-ca77-4a69-b133-1c95be39ea84
		summarizeBy: none
		sourceColumn: Lineup Slot

		annotation SummarizationSetBy = Automatic

	column SlotDescription
		dataType: string
		lineageTag: 9ec7041e-056c-488b-b0a0-0bf6d03e3df5
		summarizeBy: none
		sourceColumn: SlotDescription

		annotation SummarizationSetBy = Automatic

	partition PlayersTable = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\playerstable.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Week", Int64.Type}, {"FantasyTeam", type text}, {"NFL_Team", type text}, {"Player Name", type text}, {"Status", type text}, {"Lineup Slot", type text}, {"PlayerKey", type text}, {"MatchupKey", type text}, {"Home", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"FantasyTeam", "Fantasy Name"}, {"NFL_Team", "Team City"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Home"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "SlotDescription", each if Text.Contains([Lineup Slot],"BE") then "Bench" else if [Lineup Slot]="K" then "Kicker" else if [Lineup Slot]="D/ST" then "D/ST" else "Active Roster")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

