table PlayerPointsStats
	lineageTag: 81942150-b37b-4a81-a511-f30e725da61a

	column NFL_Team
		dataType: string
		lineageTag: 857511e5-f44d-4ac0-94bf-8d4213907811
		summarizeBy: none
		sourceColumn: NFL_Team

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 5afe4f07-3500-4839-b9a9-c2c3912e77e1
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 0527c5bd-7413-455b-8494-28f40e843067
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bc9c76dd-0ca7-420c-90f3-efd49722c8e5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column PointsPerItem
		dataType: double
		lineageTag: 5a59e73a-9bb5-408c-9fe2-1144eecb6379
		summarizeBy: sum
		sourceColumn: PointsPerItem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalPoints
		dataType: double
		lineageTag: 7521cc1f-ddee-444c-8de6-98c88430b528
		summarizeBy: sum
		sourceColumn: TotalPoints

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlayerKey
		dataType: string
		lineageTag: 15660e19-314b-4aa4-be39-629f6b305457
		summarizeBy: none
		sourceColumn: PlayerKey

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 8171405a-8a24-467e-8703-c4cf53509bec
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column FantasyTeam
		dataType: string
		lineageTag: 724ceb03-639b-47a0-8791-45562b00eb38
		summarizeBy: none
		sourceColumn: FantasyTeam

		annotation SummarizationSetBy = Automatic

	column 'Player Name'
		dataType: string
		lineageTag: 4e07ef76-fd26-4f21-838d-451aba372e1c
		summarizeBy: none
		sourceColumn: Player Name

		annotation SummarizationSetBy = Automatic

	column PlayerID
		dataType: int64
		formatString: 0
		lineageTag: 7c384913-ab3e-401d-93b7-e13bda1fe3e8
		summarizeBy: count
		sourceColumn: PlayerID

		annotation SummarizationSetBy = Automatic

	column Headshot_url
		dataType: string
		lineageTag: 41af25dd-2db8-467b-a9a5-5a7102c5dbc5
		summarizeBy: none
		sourceColumn: Headshot_url

		annotation SummarizationSetBy = Automatic

	column Opponent
		dataType: string
		lineageTag: 4e5f1fad-030a-48b0-afb8-2cd9d7292548
		summarizeBy: none
		sourceColumn: Opponent

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 8d3e10ff-5248-4cc5-be62-1930b4c39c11
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column PositionRank
		dataType: string
		lineageTag: 0006baf5-c379-4929-a06a-9a495b0d83a8
		summarizeBy: none
		sourceColumn: PositionRank

		annotation SummarizationSetBy = Automatic

	column Bye
		dataType: int64
		formatString: 0
		lineageTag: aa1c9f7c-d47d-4e5f-a4ce-7a857f37583d
		summarizeBy: sum
		sourceColumn: Bye

		annotation SummarizationSetBy = Automatic

	column Projected
		dataType: double
		lineageTag: feeb6042-ce32-4212-b602-321633f2e3c0
		summarizeBy: sum
		sourceColumn: Projected

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Actual
		dataType: double
		lineageTag: f2e753c9-a0ea-4ef6-bebc-9fe880f9682e
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Home
		dataType: string
		lineageTag: 72f36756-f538-4737-b71d-0a02118c06e8
		summarizeBy: none
		sourceColumn: Home

		annotation SummarizationSetBy = Automatic

	column 'Lineup Slot'
		dataType: string
		lineageTag: ceb6ad73-ea46-462c-a38c-053d285ac8fd
		summarizeBy: none
		sourceColumn: Lineup Slot

		annotation SummarizationSetBy = Automatic

	partition PlayerPointsStats = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\playerpointsnew.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Week", Int64.Type}, {"FantasyTeam", type text}, {"Player Name", type text}, {"PlayerID", Int64.Type}, {"Headshot_url", type text}, {"Status", type text}, {"NFL_Team", type text}, {"Opponent", type text}, {"Position", type text}, {"PositionRank", type text}, {"PlayerKey", type text}, {"Bye", Int64.Type}, {"Projected", type number}, {"Actual", type number}, {"Attribute", type text}, {"Value", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Attribute"}, PointsMap, {"Stat"}, "PointsMap", JoinKind.LeftOuter),
				    #"Expanded PointsMap" = Table.ExpandTableColumn(#"Merged Queries", "PointsMap", {"Points"}, {"Points"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PointsMap",{{"Points", "PointsPerItem"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns1", "TotalPoints", each [Value]*[PointsPerItem]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"TotalPoints", type number}}),
				    #"Rounded Off" = Table.TransformColumns(#"Changed Type3",{{"TotalPoints", each Number.Round(_, 2), type number}})
				in
				    #"Rounded Off"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

