table PlayerPointsStats
	lineageTag: 81942150-b37b-4a81-a511-f30e725da61a

	column Attribute
		dataType: string
		lineageTag: 5afe4f07-3500-4839-b9a9-c2c3912e77e1
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 0527c5bd-7413-455b-8494-28f40e843067
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column TotalPoints
		dataType: double
		lineageTag: 7521cc1f-ddee-444c-8de6-98c88430b528
		summarizeBy: sum
		sourceColumn: TotalPoints

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlayerKey
		dataType: string
		lineageTag: 15660e19-314b-4aa4-be39-629f6b305457
		summarizeBy: none
		sourceColumn: PlayerKey

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 8171405a-8a24-467e-8703-c4cf53509bec
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column FantasyTeam
		dataType: string
		lineageTag: 724ceb03-639b-47a0-8791-45562b00eb38
		summarizeBy: none
		sourceColumn: FantasyTeam

		annotation SummarizationSetBy = Automatic

	column 'Player Name'
		dataType: string
		lineageTag: 4e07ef76-fd26-4f21-838d-451aba372e1c
		summarizeBy: none
		sourceColumn: Player Name

		annotation SummarizationSetBy = Automatic

	column Headshot_url
		dataType: string
		lineageTag: 41af25dd-2db8-467b-a9a5-5a7102c5dbc5
		summarizeBy: none
		sourceColumn: Headshot_url

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: 8d3e10ff-5248-4cc5-be62-1930b4c39c11
		summarizeBy: none
		sourceColumn: Position
		sortByColumn: PositionIndex

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: double
		lineageTag: f2e753c9-a0ea-4ef6-bebc-9fe880f9682e
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lineup Slot'
		dataType: string
		lineageTag: ceb6ad73-ea46-462c-a38c-053d285ac8fd
		summarizeBy: none
		sourceColumn: Lineup Slot

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7c675aaf-21d9-4c60-a6ef-516b041c19e8
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Condensed Attribute'
		dataType: string
		lineageTag: ed000a54-0bf3-44e4-8997-6241bcdf9a7f
		summarizeBy: none
		sourceColumn: Condensed Attribute
		sortByColumn: CondensedIndex

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CondensedIndex
		dataType: int64
		formatString: 0
		lineageTag: 703808f7-62f1-4107-958b-9bfc9192d771
		summarizeBy: sum
		sourceColumn: CondensedIndex

		annotation SummarizationSetBy = Automatic

	column PositionIndex
		dataType: string
		lineageTag: 7b789be1-19f2-472e-8961-0234d2a05892
		summarizeBy: none
		sourceColumn: PositionIndex

		annotation SummarizationSetBy = Automatic

	partition PlayerPointsStats = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\playerpointsnew.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Week", Int64.Type}, {"FantasyTeam", type text}, {"Player Name", type text}, {"PlayerID", Int64.Type}, {"Headshot_url", type text}, {"Status", type text}, {"NFL_Team", type text}, {"Opponent", type text}, {"Position", type text}, {"PositionRank", type text}, {"PlayerKey", type text}, {"Bye", Int64.Type}, {"Projected", type number}, {"Actual", type number}, {"Attribute", type text}, {"Value", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Attribute"}, PointsMap, {"Stat"}, "PointsMap", JoinKind.LeftOuter),
				    #"Expanded PointsMap" = Table.ExpandTableColumn(#"Merged Queries", "PointsMap", {"Category", "Points"}, {"Category", "Points"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PointsMap",{{"Points", "PointsPerItem"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns1", "TotalPoints", each [Value]*[PointsPerItem]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"TotalPoints", type number}}),
				    #"Rounded Off" = Table.TransformColumns(#"Changed Type3",{{"TotalPoints", each Number.Round(_, 2), type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Rounded Off",{"Opponent", "NFL_Team", "Home", "Status", "PositionRank", "Projected", "PlayerID", "Bye", "PointsPerItem"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Condensed Attribute", each if [Attribute] = "Passing Yards" then "YDS" else if [Attribute] = "TD Pass" then "TD" else if [Attribute] = "Interceptions Thrown" then "INT" else if [Attribute] = "Receiving Targets" then "TAR" else if [Attribute] = "Each Reception" then "REC" else if [Attribute] = "Rushing Attempts" then "YDS" else if [Attribute] = "Rushing Yards" then "YDS" else if [Attribute] = "TD Rush" then "TD" else if [Category] = "Kicking" then [Attribute] else if [Category] = "D/ST" then [Attribute] else if [Attribute] = "TD Reception" then "TD" else if [Attribute]="PA" then "PA" else if [Attribute]="YA" then "YA" else "Other"),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom", "Condensed Attribute2", each if [Condensed Attribute] = "Each PAT Made" then "PATs Made" else if [Condensed Attribute] = "PAT Attempt" then "PAT Attempts" else if [Condensed Attribute] = "FG Made (0-39 yards)" then "1-39" else if [Condensed Attribute] = "FG Made (40-49 yards)" then "40-49" else if [Condensed Attribute] = "FG Made (50-59 yards)" then "50-59" else if [Condensed Attribute] = "FG Made (60+ yards)" then "60+" else if [Condensed Attribute] = "Field Goal Attempted" then "FG Attempts" else if [Condensed Attribute] = "Each Sack" then "Sack" else if Text.Contains([Condensed Attribute], "TD") then "TD" else if Text.Contains([Condensed Attribute], "Block") then "Block" else if [Condensed Attribute] = "Each Interception" then "INT" else if [Condensed Attribute] = "Each Fumble Recovered" then "FR" else if [Condensed Attribute] = "Each Safety" then "Safety" else if [Condensed Attribute] = null then null else [Condensed Attribute]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"Condensed Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Condensed Attribute2", "Condensed Attribute"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns", "CondensedIndex", each if [Condensed Attribute]="REC" then 1 else if [Condensed Attribute]="CAR" then 2 else if [Condensed Attribute]="YDS" then 3 else if [Condensed Attribute]="TD" then 4 else if [Condensed Attribute]="TAR" then 5 else if [Condensed Attribute]="INT" then 6 else if [Condensed Attribute]="1-39" then 7 else if [Condensed Attribute]="40-49" then 8 else if [Condensed Attribute]="50-59" then 9 else if [Condensed Attribute]="60+" then 10 else if [Condensed Attribute]="FG Attempts" then 11 else if [Condensed Attribute]="PAT Attempts" then 12 else if [Condensed Attribute]="PATs Made" then 13 else if [Condensed Attribute]="FR" then 14 else if [Condensed Attribute]="Sack" then 15 else if [Condensed Attribute]="Safety" then 16 else if [Condensed Attribute]="Block" then 17 else if [Condensed Attribute]="PA" then 18 else if [Condensed Attribute]="YA" then 19 else 20),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom3",{{"CondensedIndex", Int64.Type}, {"Condensed Attribute", type text}, {"Lineup Slot", type text}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type1", "PositionIndex", each if [Position]="QB" then 1 else if [Position]="RB" then 2 else if [Position]="WR" then 3 else if [Position]="TE" then 4 else if [Position]="K" then 5 else if [Position]="D/ST" then 6 else 7)
				in
				    #"Added Custom4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

