table 'Power Rankings'
	lineageTag: 20859478-2046-456a-9b00-2b2904fa5681

	column Team
		dataType: string
		lineageTag: 85c93d59-9775-43c8-9918-6cea71269a06
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: b39e0a9a-d146-4ec0-9ce2-b7530842b58a
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 5cb7fd05-15af-4671-9f03-0b5e78aef1fa
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	partition 'Power Rankings' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\power_ranking.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Team", type text}, {"Week", Int64.Type}, {"Rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

