table TeamsTable
	lineageTag: fe9fd550-8518-4fbf-8b4d-710dd1b4fa6a

	column 'Manager Name'
		dataType: string
		lineageTag: a82ee3b8-459a-4973-9f1a-5c8bef25decc
		summarizeBy: none
		sourceColumn: Manager Name

		annotation SummarizationSetBy = Automatic

	column 'Fantasy Name'
		dataType: string
		lineageTag: 82da9a19-a522-4ada-9ccc-82072b71a48b
		summarizeBy: none
		sourceColumn: Fantasy Name

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 13cc267b-0c83-4440-a197-7e929c5ac108
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: ad8a19d5-052e-4b0b-a122-846760d08fb5
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column Acronym
		dataType: string
		lineageTag: b623daeb-8abc-4f77-acdb-db08538a9790
		summarizeBy: none
		sourceColumn: Acronym

		annotation SummarizationSetBy = Automatic

	partition TeamsTable = m
		mode: import
		queryGroup: Main
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Fantasy Football 24\fantasyTeams_df.xlsx"), null, true),
				    TeamsTable_Table = Source{[Item="TeamsTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TeamsTable_Table,{{"Manager Name", type text}, {"Fantasy Name", type text}, {"Division", type text}, {"Image", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

